global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#александр-ильдяков'
