comment:
  image:
    repository: drsklif/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: drsklif/post
    tag: 0.0.2
    service:
      externalPort: 5000

ui:
  image:
    repository: drsklif/ui
    tag: latest
    service:
      externalPort: 9292