kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ojFr3vKxyA1cmGwC7z0+lWLPrvqvQD6gn+gB8uimlXo=
      - identity: {}
